name: test
on: 
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-24.04
    container: ros:humble-ros-base-jammy 
    steps:
      - uses: actions/checkout@v4
      - name: Build and Test
        shell: bash
        run: |
          mkdir -p ~/ros2_ws/src
          cp -r . ~/ros2_ws/src/register
          cd ~/ros2_ws

          apt-get update
          rosdep update
          rosdep install -i --from-path src --rosdistro humble -y

          source /opt/ros/humble/setup.sh
          colcon build

          source install/setup.bash

          bash src/register/test/test.bash
